name: Update Repository
on:
  schedule: 
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  upload_job:
    runs-on: ubuntu-latest
    name: update
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configuration
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_NAME }}"
      - name: Download
        run: |
          wget https://lincgeek.org/bashpodder/bashpodder.shell -O bashpodder.shell
          wget https://lincgeek.org/bashpodder/parse_enclosure.xsl -O parse_enclosure.xsl
          wget https://lincgeek.org/bashpodder/bp.conf -O bp.conf
      - name: Commit
        run: |
          git add .
          git commit -m "$(date +%Y%d%m)"
      - name: Push
        run: git push
